services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/app
    stdin_open: true
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 5s
      retries: 20
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

